### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sgrastar** [sgrastar/HARlytics#1]
## Implemented by v.0.5.0
- [x]  #8 
- [x]  #5 

## Implemented by v.1.0.0
- [x]  Save sequence diagrams as images
- [x] Display of the error report screen when an error occurs when loading a file
- [ ]  #7 
- [ ]  #3 
- [x] #6 
- [ ] #10 
- [ ] #11 
- [ ] #9 
- [ ] #13 

## Implemented by v.2.0.0
- [ ]  Compare two HAR files
- [ ]  Add SAML/OIDC-specific views
- [ ] Improved Statistics tab
- [ ]  Add features for Loading performance (LCP) analysis

## CI/CD
- [x] Auto update/publish to Chrome Webstore
- [x] Auto update/publish to Microsoft Edge Add-on store
- [ ] Auto release note

## Others
- [x] Published to Chrome Web Store
- [x] Published to Microsoft Edge Add-on
- [x] Create Website ( https://github.com/sgrastar/HARlytics-website )

## Implementation undecided
This item is under consideration for implementation.
- Display raw .har file
- Add View using the initiator information in the HAR file
- Improved filtering by domain (string filtering before select domain)
- Feature that modify HAR file
- Support mobile phone browser
- E2E Test
